"""user_profiles

Revision ID: 3f78f3beb263
Revises: be12aa2b742b
Create Date: 2026-08-06 20:18:09.994114

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f78f3beb263"
down_revision: str | Sequence[str] | None = "be12aa2b742b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resume_text", sa.Text(), nullable=True),
        sa.Column("raw_prefs_text", sa.Text(), nullable=True),
        sa.Column(
            "structured_prefs", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
