"""add user_profile name

Revision ID: db8ff0c26fe0
Revises: 8c9314cfd944
Create Date: 2026-08-07 10:14:34.520369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8ff0c26fe0'
down_revision: Union[str, Sequence[str], None] = '8c9314cfd944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'name')
    # ### end Alembic commands ###
